/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_demo_JNIgetch */

#ifndef _Included_com_jni_demo_JNIgetch
#define _Included_com_jni_demo_JNIgetch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_demo_JNIgetch
 * Method:    getch
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_jni_demo_JNIgetch_getch
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
